### ISSUE TITLE
Help me to fix this issue ... 

### ISSUE THREAD

**Issue by kishanmakkar007** [XeroAPI/Xero-NetStandard#162]
Application startup exception: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'get_RootElement' in type 'Xero.NetStandard.OAuth2.Client.CustomJsonCodec' from assembly 'Xero.NetStandard.OAuth2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.Extensions.DependencyInjection.MvcCoreMvcBuilderExtensions.AddControllersAsServices(IMvcBuilder builder)
   at Nop.Web.Framework.Infrastructure.Extensions.ServiceCollectionExtensions.AddNopMvc(IServiceCollection services) in C:\andrei\nopcommerce\sources\src\Presentation\Nop.Web.Framework\Infrastructure\Extensions\ServiceCollectionExtensions.cs:line 326
   at Nop.Web.Framework.Infrastructure.NopMvcStartup.ConfigureServices(IServiceCollection services, IConfiguration configuration) in C:\andrei\nopcommerce\sources\src\Presentation\Nop.Web.Framework\Infrastructure\NopMvcStartup.cs:line 31
   at Nop.Core.Infrastructure.NopEngine.ConfigureServices(IServiceCollection services, IConfiguration configuration, NopConfig nopConfig) in C:\andrei\nopcommerce\sources\src\Libraries\Nop.Core\Infrastructure\NopEngine.cs:line 167
   at Nop.Web.Framework.Infrastructure.Extensions.ServiceCollectionExtensions.ConfigureApplicationServices(IServiceCollection services, IConfiguration configuration, IHostingEnvironment hostingEnvironment) in C:\andrei\nopcommerce\sources\src\Presentation\Nop.Web.Framework\Infrastructure\Extensions\ServiceCollectionExtensions.cs:line 83
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
System.TypeLoadException: Method 'get_RootElement' in type 'Xero.NetStandard.OAuth2.Client.CustomJsonCodec' from assembly 'Xero.NetStandard.OAuth2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
      Application startup exception
      Method 'get_RootElement' in type 'Xero.NetStandard.OAuth2.Client.CustomJsonCodec' from assembly 'Xero.NetStandard.OAuth2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'get_RootElement' in type 'Xero.NetStandard.OAuth2.Client.CustomJsonCodec' from assembly 'Xero.NetStandard.OAuth2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.Extensions.DependencyInjection.MvcCoreMvcBuilderExtensions.AddControllersAsServices(IMvcBuilder builder)
   at Nop.Web.Framework.Infrastructure.Extensions.ServiceCollectionExtensions.AddNopMvc(IServiceCollection services) in C:\andrei\nopcommerce\sources\src\Presentation\Nop.Web.Framework\Infrastructure\Extensions\ServiceCollectionExtensions.cs:line 326
   at Nop.Web.Framework.Infrastructure.NopMvcStartup.ConfigureServices(IServiceCollection services, IConfiguration configuration) in C:\andrei\nopcommerce\sources\src\Presentation\Nop.Web.Framework\Infrastructure\NopMvcStartup.cs:line 31
   at Nop.Core.Infrastructure.NopEngine.ConfigureServices(IServiceCollection services, IConfiguration configuration, NopConfig nopConfig) in C:\andrei\nopcommerce\sources\src\Libraries\Nop.Core\Infrastructure\NopEngine.cs:line 167
   at Nop.Web.Framework.Infrastructure.Extensions.ServiceCollectionExtensions.ConfigureApplicationServices(IServiceCollection services, IConfiguration configuration, IHostingEnvironment hostingEnvironment) in C:\andrei\nopcommerce\sources\src\Presentation\Nop.Web.Framework\Infrastructure\Extensions\ServiceCollectionExtensions.cs:line 83
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
System.TypeLoadException: Method 'get_RootElement' in type 'Xero.NetStandard.OAuth2.Client.CustomJsonCodec' from assembly 'Xero.NetStandard.OAuth2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Hosting environment: Production
Content root path: C:\inetpub\wwwroot\nop42new
Now listening on: http://127.0.0.1:27656
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://nop42.tmotions.com/Admin/Plugin/List  
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 71.2653ms 500 text/html; charset=utf-8
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://nop42.tmotions.com/favicon.ico  
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.3581ms 500 text/html; charset=utf-8

**Comment by jenksguo** [comment]
Hi @kishanmakkar007 could you please share the snippet that triggers this exception?

What framework are you using to develop? dotnet core or dotnet framework?

**Comment by jenksguo** [comment]
Hi @kishanmakkar007 please provide some more info so we can help you.
