### ISSUE TITLE
XeroClient.RequestAccessTokenAsync can lead to JsonSerializationException

### ISSUE THREAD

**Issue by dllmr** [XeroAPI/Xero-NetStandard#212]
**SDK you're using (please complete the following information):**
 - Version 3.2.1

**Describe the bug**
Depending on the companies for which a user is authorised, a JSON serialization exception can occur in XeroClient.GetConnectionsAsync called from XeroClient.RequestAccessTokenAsync. See stack trace below. In our case, the authorised companies were a genuine paid Xero account, plus the Demo Company (UK) which had expired. I'm wondering if the expiry of the demo company was a factor.

**Additional context**
Stack trace...
`Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'System.Guid'. Path '[0].authEventId', line 1, position 64. ---> System.ArgumentException: Could not cast or convert from {null} to System.Guid.
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Xero.NetStandard.OAuth2.Client.XeroClient.<GetConnectionsAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Xero.NetStandard.OAuth2.Client.XeroClient.<RequestAccessTokenAsync>d__11.MoveNext()`

**Comment by sazaang1** [comment]
Hi @jenksguo, I have got this error as well. 
When OAuth 1.0a token migrated to OAuth 2.0, AuthEventId is null. so when I try to connect another app with Xero it throws an exception "Error converting value {null} to type 'System.Guid'. Path '[0].authEventId'" while exchanging code to token as the authEventId is null in migrated app. Do you have any plan to change AuthEventId In Tenant model to nullable Guid?

**Comment by jenksguo** [comment]
Hey @sazaang1 yup, this makes a lot of sense thanks for feeding this to me. I will get it changed on the next release, hopefully this week.

**Comment by jenksguo** [comment]
Hi @sazaang1 @dllmr, I have made authEventId nullable now, please check out [v1.1.1](https://www.nuget.org/packages/Xero.NetStandard.OAuth2Client/1.1.1). 

Please reopen this issue if you find anything else related to this.
