### ISSUE TITLE
Can't request more than 55 invoices

### ISSUE THREAD

**Issue by nganbread** [XeroAPI/Xero-NetStandard#413]
**SDK you're using (please complete the following information):**
```xml
    <PackageReference Include="Xero.NetStandard.OAuth2" Version="3.20.0" />
    <PackageReference Include="Xero.NetStandard.OAuth2Client" Version="1.5.1" />
```

**Describe the bug**
When requesting more than 55 items a 404 is returned. 

First discovered using the client, but I have also reproduced the bug using the API

**To Reproduce**

### Client
```
var client = new XeroClient(new XeroConfiguration
                {
                    ClientId = _options.Value.ClientId,
                    ClientSecret = _options.Value.ClientSecret
                });

                var xeroToken = await client.RequestClientCredentialsTokenAsync();
            var api = new AccountingApi();
            api.getInvoicesAsync(xeroToken,_options.Value.TenantId, iDs: moreThan55Ids);
```

Exception:
```
Xero.NetStandard.OAuth2.Client.ApiException
Xero API error calling GetInvoices: The resource you're looking for cannot be found

Xero.NetStandard.OAuth2.Client.ApiException: Xero API error calling GetInvoices: The resource you're looking for cannot be found
   at Xero.NetStandard.OAuth2.Api.AccountingApi.GetInvoicesAsyncWithHttpInfo(String accessToken, String xeroTenantId, Nullable`1 ifModifiedSince, String where, String order, List`1 iDs, List`1 invoiceNumbers, List`1 contactIDs, List`1 statuses, Nullable`1 page, Nullable`1 includeArchived, Nullable`1 createdByMyApp, Nullable`1 unitdp, Nullable`1 summaryOnly)
   at Xero.NetStandard.OAuth2.Api.AccountingApi.GetInvoicesAsync(String accessToken, String xeroTenantId, Nullable`1 ifModifiedSince, String where, String order, List`1 iDs, List`1 invoiceNumbers, List`1 contactIDs, List`1 statuses, Nullable`1 page, Nullable`1 includeArchived, Nullable`1 createdByMyApp, Nullable`1 unitdp, Nullable`1 summaryOnly)
   at MyService.Integration.Xero.Service.Integration.Xero.XeroApi.ExecuteAsync[T](Func`4 action)
   at MyService.Integration.Xero.Service.Integration.Xero.XeroApi.GetInvoicesAsync(List`1 ids, Int32 page) in D:\a\1\s\MyService.Integration.Xero.Service\Integration\Xero\XeroApi.cs:line 279
   at MyService.Integration.Xero.Service.Integration.Xero.XeroApi.GetInvoicesAsync(IEnumerable`1 ids) in D:\a\1\s\MyService.Integration.Xero.Service\Integration\Xero\XeroApi.cs:line 259
   at MyService.Integration.Xero.Service.Integration.Xero.XeroService.UpdateIncompleteInvoicesAsync(PerformContext context) in D:\a\1\s\MyService.Integration.Xero.Service\Integration\Xero\XeroService.cs:line 216
```

## API

```
GET /api.xro/2.0/Invoices?page=0&IDs={56 GUIDS here} HTTP/1.1
Host: api.xero.com
Content-Type: application/json
Authorization: Bearer <removed>
Cookie: <removed>
```

```
404
The resource you're looking for cannot be found
```

**Expected behavior**
All items are returned

**Comment by nganbread** [comment]
When performing a request with 55 IDs the request is successful. I've also checked that the 56th invoice does indeed exist

**Comment by RettBehrens** [comment]
Hey @nganbread sounds like the 56th ID causes the url for your query to exceed the limit.

From our docs on [requests and responses](https://developer.xero.com/documentation/api/accounting/requests-and-responses/#http-get):

> Retrieving a filtered set of resources
The number of parameters is only limited by the maximum url length. To ensure you receive a timely response from the API, we recommend you look to retrieve in a batch of 40.

**Comment by nganbread** [comment]
@RettBehrens a 404 may not be the best response code for this error

If it can't be fixed server side, perhaps a URL length check should be performed in the client?
