### ISSUE TITLE
System.MissingMethodException still an issue with RestSharp on 9.1.0

### ISSUE THREAD

**Issue by JamesOPCS** [XeroAPI/Xero-NetStandard#545]
**SDK you're using (please complete the following information):**
 - Version 9.1.0

**Describe the bug**
So effectively it is the same issue as reported in the below, except it is still happening in version 9.1.0:
https://github.com/XeroAPI/Xero-NetStandard/issues/513

I note that in the comments it says the following:

"We have replaced RestSharp with core httpClient library in our new Dotnet SDK version 9.0.0

Please install the latest version and hopefully RestSharp issue will not occur anymore."

However, if you update RestSharp beyond 110.2.0 then I get the following:

Method not found: 'Void RestSharp.RestRequest.set_Timeout(Int32)'.    at Xero.NetStandard.OAuth2.Client.ApiClient.newRequest(HttpMethod method, String path, RequestOptions options, IReadableConfiguration configuration)
   at Xero.NetStandard.OAuth2.Client.ApiClient.<GetAsync>d__9`1.MoveNext()

**To Reproduce**
Same as other issue linked but to be clear:
1. Upgrade to the latest version of RestSharp.
2. Call the GetInvoicesAsync method.

**Expected behavior**
Return list of invoices.

Thanks, hopefully someone can help 🤞

**Comment by DanPatten** [comment]
Restsharp is not included in the latest version: 

https://github.com/XeroAPI/Xero-NetStandard/commit/6b441d31166d6cfda23417bb2d9662328d3ebe8c

**Comment by JamesOPCS** [comment]
> Restsharp is not included in the latest version:
> 
> [6b441d3](https://github.com/XeroAPI/Xero-NetStandard/commit/6b441d31166d6cfda23417bb2d9662328d3ebe8c)

This is what I thought too. However, I'm still getting the issue even after updating.
