### ISSUE TITLE
Unable to edit an invoice with payment applied

### ISSUE THREAD

**Issue by pajohns** [XeroAPI/Xero-NetStandard#84]
Despite being able to edit an invoice in Xero to change the description or the customer associated with an invoice, once a payment has been applied requests are rejected from Xero disallowing any editing of said invoice. I notice that according to [this](https://community.xero.com/business/discussion/51271/) the ability to edit an invoice with part payment has been enabled, so why are the requests being rejected?

## Steps to reproduce
Execute the following which retrieves a valid invoice, modifies the reference and performs an update.
```csharp
Invoice xeroInvoice = await m_api.Invoices.FindAsync(model.XeroId);
xeroInvoice.Reference = model.Current.Description;
xeroInvoice = await m_api.Invoices.UpdateAsync(xeroInvoice);
```

The following exception is thrown

```
Error Portal.Accounting.Services.XeroInvoiceService Validation error while editing an invoice. This document cannot be edited as it has a payment or credit note allocated to it.    at Xero.Api.Infrastructure.Http.XeroHttpClient.HandleErrorsAsync(HttpResponseMessage response)
   at Xero.Api.Infrastructure.Http.XeroHttpClient.ReadAsync[TResult,TResponse](HttpResponseMessage response)
   at Xero.Api.Infrastructure.Http.XeroHttpClient.PostAsync[TResult,TResponse](String endpoint, Object data, NameValueCollection parameters)
   at Xero.Api.Core.Endpoints.Base.XeroUpdateEndpoint`4.PostAsync(TRequest data)
   at Xero.Api.Core.Endpoints.Base.XeroUpdateEndpoint`4.UpdateAsync(TResult item)
   at Portal.Accounting.Services.XeroInvoiceService.UpdateInvoice(SaleOrder model) in C:\Users\philip.johns\reps\portal\src\Portal.Accounting\Services\XeroInvoiceService.cs:line 143
```

**Comment by SidneyAllen** [comment]
@pajohns - Sorry for the slow reply to your question.  In order to edit an invoice after a payment or partial payment has been applied is to "remove" the payment.  Update the invoice, then recreate the payment.

You can delete a payment by performing an update and passing in a payment object with STATUS = DELETED
